OFFICE OF THE DEPUTY DIRECTOR (L&E)

DELHI JAL BOARD: GOVT OF N.C.T. OF DELHI

VARUNAJAYA PHASE-II, KAROL BAGH, NEW DELHI

Ph. No. 011-23521266, e-mail-acle309@gmail.com

No. DJB/Dy.Dir:(L&E)/Allot./2023/254/

Dated: 20-07-2023

Circular

Competent Authority has decided to consider the applications received during 01-01-2023 to 31-03-2023 for quarter allotment and allot type-I, type-II & type-III departmental accommodations as per Govt. Accommodation Rules.

In pursuance of above decision, a provisional seniority list in respect of applications received during 01-01-2023 to 31-03-2023 (in hard copy), have been prepared. The said seniority list has been uploaded on the website of DJB portal, under "Circular" head as well as displayed on the notice board of the office of Dy. Dir. (L&E), Room No. 309, Varunalaya Phase-II. All the applicants who have applied during above said period are requested to check their details in the seniority list and furnish objections, if any, latest by 27-07-2023. Thereafter, the list will be finalized and allotment on the basis of final seniority list will be made amongst the vacant quarters, vacated upto 31-03-2023.

All DDO's are requested to give wide publicity of this Circular and also requested to download the seniority list for information of all the officials working under their control.

All DDO's/ Controlling Officer

Copy to:

1. Dir. (A&P)/ Dir.(F8&A)/ Vig./ Secretary/ L.O./ Dir(SDM)/ T8&QC/All ACE's/

PR/ GAB:

2. All J.L. Dir. (Rev)/All Dy. Dir.

3. PS to CEO

4. PS/PA to Member(A)/(F).WS/DOR/CVO/Addl. CEO/All CE's

E.E.(EDP) with request to upload the circular and provisional seniority list on

DJB Website

6. Office Order Book (L&E)

Deputy Director (L&E)

Addl. Chief Engineer (Proc)/.

Epo Cell, Opte Jal Board, GNCTD

Dy. No. L&E. 01-07-2023

_POFFICE OF THE DEPUTY DIRECTOR (L&E)

DELHI JAL BOARD: GOVT OF N.C.T. OF DELHI

VARUNALAYA PHASE-II, KAROL BAGH, NEW DELHI

Ph. No. 011-23521266, e-mail-acle309@gmail.com

No. DJB/Dy.Dir.(L&E)/Allot./2023/

Dated: & 07-2023

Circular

Competent Authority has decided to consider the applications received during 01-01-2023 to 31-03-2023 for quarter allotment and allot type-I, type-II & type-III departmental accommodations as per Govt. Accommodation Rules.

In pursuance of above decision, a provisional seniority list in respect of applications received during 01-01-2023 to 31-03-2023 (in hard copy), have been prepared. The said seniority list has been uploaded on the website of DJB portal, under "Circular" head as well as displayed on the notice board of the office of Dy. Dir. (L&E), Room No. 309, Varunalaya Phase-II. All the applicants who have applied during above said period are requested to check their details in the seniority list and furnish objections, if any, later by 27-07-2023. Thereafter, the list will be finalized and allotment on the basis of final seniority list will be made amongst the vacant quarters, vacated upto 31-03-2023.

All DDO's are requested to give wide publicity of this Circular and also requested to download the seniority list for information of all the officials working under their control.

All DDO's/ Controlling Officer

Copy to:

1 Dir. (A&P)/ Dir.(F&A)/ Vig./ Secretary/ L.O./ Dir(SDM)/ T8&QC/All ACE's/ PR/ GAB.

2 All Jt. Dir. (Rev)/All Dy. Dir.

3 PS to CEO

4 PS/PA to Member(A)/(F), WS/DOR/CVO/Addl. CEO/All CE's

5 E.E.(EDP) with request to upload the circular and provisional seniority list on DJB Website

6 Office Order Book (L&E)

Deptury Director (L&E)